apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{ values.component_id | dump }}}
  description: The apis.guru REST API
spec:
  type: openapi
  lifecycle: production
  owner: user:guest
  definition:
    $openapi: https://api.apis.guru/v2/openapi.yaml