---
swagger: "2.0"
info:
  description: ${{ values.description }}
  title: ${{ values.component_id }}
  version: 1.0.0
consumes:
- application/io.goswagger.examples.todo-list.v1+json
produces:
- application/io.goswagger.examples.todo-list.v1+json
schemes:
- http
paths:
  /:
    get:
      tags:
        - sites
      parameters:
        - name: since
          in: query
          type: integer
          format: int64
        - name: limit
          in: query
          type: integer
          format: int32
          default: 20
      responses:
        200:
          description: list sites
          schema:
            type: array
            items:
              $ref: "#/definitions/site"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
    post:
      tags:
        - sites
      operationId: addOne
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/site"
      responses:
        201:
          description: Created
          schema:
            $ref: "#/definitions/site"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
  /{id}:
    parameters:
      - type: integer
        format: int64
        name: id
        in: path
        required: true
    put:
      tags: ["sites"]
      operationId: updateOne
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/site"
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/site"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
    delete:
      tags:
        - sites
      operationId: destroyOne
      parameters:
        - type: integer
          format: int64
          name: id
          in: path
          required: true
      responses:
        204:
          description: Deleted
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
definitions:
  environment:
    type: object
    required: 
      - name
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      name:
        type: string
        minLength: 1
  domain:
    type: object
    required:
      - name
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      name:
        type: string
        minLength: 1
  site:
    type: object
    required:
      - domains
      - environments
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      description:
        type: string
        minLength: 1
      domains:
        type: array
        minItems: 1
        items:
          $ref: "#/definitions/domain"
      environments:
        type: array
        minItems: 1
        items:
          $ref: "#/definitions/environment"
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string